### PR TITLE
Keen refactor

### PR DESCRIPTION
**Pull request by arikgadye**

### CODE REVIEW

**Comment by chrylis** [comment]
Please modify `keenConfig.js` to check whether the values are present. If they're not, instead return an object that routes send-event to `console.log`.

**Comment by arikgadye** [comment]
so console.log() what would be the keen object?

**Comment by chrylis** [comment]
Right. Basically something like this:

```
return {
    addEvent: function(collection, data) {
        console.log("Keen event to " + collection + ": " + JSON.stringify(data));
    }
}
```

**Comment by chrylis** [comment]
ok to test

**Pull request merged**
