### PR TITLE
include new function for using tiff.js rather than tiff-js skip ci

### PR DESCRIPTION
**Pull request by arikgadye**
@chrylis this: https://raw.githubusercontent.com/seikichi/tiff.js/master/tiff.js is what i downloaded and included in vendor, and have changed line 1009 to increase the memory. You have better knowledge of this stuff, so i'll leave memory allocation to you, as well as how we would like to include this module.

### CODE REVIEW

**Comment by chrylis** [comment]
You didn't actually include the relevant artifact as a dependency or check it in to source control...

**Comment by chrylis** [comment]
And it doesn't look like you updated the dependent code sanely. You're using a global object `Tiff` for some reason.

**Comment by arikgadye** [comment]
Please don't tell me I didn't do something sanely; not specific or actionable feedback for me to act on. I do understand that it should probably be wrapped in its own amd, i was mostly pushing this to show you a potential solution to our problem, and included a link to the file in use; didn't want to force push something inside of vendor, but maybe that was the proper thing to do.

**Comment by chrylis** [comment]
I mean, specifically, that you edited a couple of lines in our module that seem to refer to some external something that isn't wired into it and that isn't present in the codebase.

**Comment by chrylis** [comment]
Actionable: [The console from the Details link above](https://artsquare.ci.cloudbees.com/job/CanIPrintIt/12/console)

**Pull request closed without merging**
