### PR TITLE
Initial view setup; need to refine and style some things such as error message and loader

### PR DESCRIPTION
**Pull request by arikgadye**
screen shot 2015-01-27 at 8 42 07 pm
screen shot 2015-01-27 at 8 42 33 pm
currently, editable form shows up after initial image input.

### CODE REVIEW

**Comment by chrylis** [comment]
Why did you modify this from the side-by-side we'd talked about? This certainly does take up a good bit of vertical space, but you didn't mention the reformat. Additionally, the "good" styling needs an exclamation point instead of a check, and I think the "bad" should have an X instead.

**Comment by arikgadye** [comment]
IMO the side by side is a bit distracting and takes the user away from the main action we want them to take, which is uploading a file. Figure this is a compromise on both, where they can upload an image, and THEN start playing around. We can discuss UI and switching back to the side by side is easy.

**Comment by chrylis** [comment]
Only distracting if we don't make the drop target significantly visually distinctive, which needs to happen anyway (it's boilerplate and not very interesting right now).

**Comment by chrylis** [comment]
We also need to include some text to explain exactly what the check/bang/X mean. That might be hackable in CSS or might be better done in-template.

**Pull request merged**
